version: "2"
services:

    worker:
        image: registry.cn-hangzhou.aliyuncs.com/lisong/weixin-public-developer:$(VERSION)
        networks:
            - frontend
        depends_on:
            - redis
        ports:
            - "8080:vim "

